#!/bin/bash

# Vercel Environment Variables Setup Helper
# This script displays all the environment variables you need to add to Vercel

echo "=========================================="
echo "VERCEL ENVIRONMENT VARIABLES"
echo "=========================================="
echo ""
echo "Copy each of these to Vercel Dashboard:"
echo "Settings → Environment Variables"
echo ""
echo "-------------------------------------------"
echo "Variable 1: NEXT_PUBLIC_SUPABASE_URL"
echo "-------------------------------------------"
echo "NEXT_PUBLIC_SUPABASE_URL=https://twsrrrejfpdqrptspgyh.supabase.co"
echo ""
echo "-------------------------------------------"
echo "Variable 2: SUPABASE_SERVICE_ROLE_KEY"
echo "-------------------------------------------"
echo "SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3c3JycmVqZnBkcXJwdHNwZ3loIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MTIyMjYwNSwiZXhwIjoyMDc2Nzk4NjA1fQ.F9t5pPL4x-R0Zu2T2jPc90nHegykyiVjEODHMVC_elA"
echo ""
echo "-------------------------------------------"
echo "Variable 3: DATABASE_URL"
echo "-------------------------------------------"
echo "DATABASE_URL=\"postgresql://postgres.twsrrrejfpdqrptspgyh:hellouser@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true&statement_cache_size=0\""
echo ""
echo "-------------------------------------------"
echo "Variable 4: DIRECT_URL"
echo "-------------------------------------------"
echo "DIRECT_URL=\"postgresql://postgres.twsrrrejfpdqrptspgyh:hellouser@aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require\""
echo ""
echo "=========================================="
echo "NEXT STEPS:"
echo "=========================================="
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Select: sandiya-hrm-redesign project"
echo "3. Click: Settings → Environment Variables"
echo "4. Add all 4 variables above"
echo "5. Set each to: Production, Preview, Development"
echo "6. Click: Redeploy on Vercel"
echo ""
